"""initial_schema

Revision ID: baa435f1aa72
Revises: 
Create Date: 2026-07-12 14:44:49.079039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'baa435f1aa72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('year_of_study', sa.Integer(), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_students_created_at', 'students', ['created_at'], unique=False)
    op.create_index('idx_students_email', 'students', ['email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('model_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prediction', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_model_predictions_created_at', 'model_predictions', ['created_at'], unique=False)
    op.create_index('idx_model_predictions_model_name', 'model_predictions', ['model_name'], unique=False)
    op.create_index('idx_model_predictions_model_name_created_at', 'model_predictions', ['model_name', 'created_at'], unique=False)
    op.create_index('idx_model_predictions_student_id', 'model_predictions', ['student_id'], unique=False)
    op.create_index('idx_model_predictions_student_id_created_at', 'model_predictions', ['student_id', 'created_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('focus_score', sa.Float(), nullable=False),
    sa.Column('inactivity_duration', sa.Integer(), nullable=False),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('wrong_answers', sa.Integer(), nullable=False),
    sa.Column('response_time', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_created_at', 'sessions', ['created_at'], unique=False)
    op.create_index('idx_sessions_engagement_score', 'sessions', ['engagement_score'], unique=False)
    op.create_index('idx_sessions_student_id', 'sessions', ['student_id'], unique=False)
    op.create_index('idx_sessions_student_id_created_at', 'sessions', ['student_id', 'created_at'], unique=False)
    op.create_index('idx_sessions_student_id_start_time', 'sessions', ['student_id', 'start_time'], unique=False)
    op.create_table('behavioral_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_behavioral_events_session_id', 'behavioral_events', ['session_id'], unique=False)
    op.create_index('idx_behavioral_events_timestamp', 'behavioral_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_behavioral_events_timestamp', table_name='behavioral_events')
    op.drop_index('idx_behavioral_events_session_id', table_name='behavioral_events')
    op.drop_table('behavioral_events')
    op.drop_index('idx_sessions_student_id_start_time', table_name='sessions')
    op.drop_index('idx_sessions_student_id_created_at', table_name='sessions')
    op.drop_index('idx_sessions_student_id', table_name='sessions')
    op.drop_index('idx_sessions_engagement_score', table_name='sessions')
    op.drop_index('idx_sessions_created_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_model_predictions_student_id_created_at', table_name='model_predictions')
    op.drop_index('idx_model_predictions_student_id', table_name='model_predictions')
    op.drop_index('idx_model_predictions_model_name_created_at', table_name='model_predictions')
    op.drop_index('idx_model_predictions_model_name', table_name='model_predictions')
    op.drop_index('idx_model_predictions_created_at', table_name='model_predictions')
    op.drop_table('model_predictions')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_students_email', table_name='students')
    op.drop_index('idx_students_created_at', table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
